PACKAGE_NAME="rk-vcodec"
PACKAGE_VERSION="1.0"
CLEAN="make clean"
MAKE[0]="make all KDIR=/lib/modules/${kernelver}/build"
BUILT_MODULE_NAME[0]="rkvenc"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
